### ISSUE TITLE
Cross-Server teleport does not work

### ISSUE THREAD

**Issue by seyfahni** [seyfahni/ProxySuite#3]
Every time someone is teleported cross-server (without cooldown) an exception on the receiving server is thrown. The player is transferred to the target server but not to the target player or location.

```
[14:11:42 WARN]: [ProxySuiteBukkit] Plugin ProxySuiteBukkit v1.2.5 generated an exception whilst handling plugin message
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_181]
        at de.sabbertran.proxysuite.bukkit.ProxySuiteBukkit.teleportRequest(ProxySuiteBukkit.java:168) ~[?:?]
        at de.sabbertran.proxysuite.bukkit.PMessageListener.onPluginMessageReceived(PMessageListener.java:78) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2697) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1586]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1586]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1586]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by seyfahni** [comment]
Seems to be caused by not waiting for the teleported player to join the server.

**Comment by Xeravax** [comment]
Will this ever be solved?
